# Generated by Django 4.2.30 on 2026-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stockpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_open', models.BooleanField(default=True)),
            ],
        ),
    ]
