# Generated by Django 4.2.30 on 2026-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_limitorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='SELL', max_length=4),
        ),
    ]
